# Generated by Django 3.1.7 on 2021-02-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('birthDate', models.DateField()),
                ('sex', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('recordDate', models.DateField()),
            ],
        ),
    ]
